### ISSUE TITLE
1월 코딩 스터디 종료! 

### ISSUE THREAD

**Issue by jiwoo-choi** [jiwoo-choi/coding-study#13]
- 1월 코딩 스터디가 종료되었습니다 
- 비록 짧은 시간이었지만 **모두 참석률이 높은 수준으로 유지된 채로 종료되었습니다**. 👏👏
- 시험도 많았고, 각자 따로 공부도 하고 계신것같은데 모두 수고하셨어요.
- 1월 참석률 100% 1위 🎉`hoonti06`님! 🎉
<img width="831" alt="스크린샷 2021-02-01 오후 12 30 17" src="https://user-images.githubusercontent.com/18345994/106412121-40c74e00-648a-11eb-8586-a952d1571e9e.png">

----
- 혹시 다음 달 스터디를 위한 피드백이 있다면 편하게 남겨주세요.

**Comment by hoonti06** [comment]
오예!

**Comment by jiwoo-choi** [comment]
@hoonti06 
같은문제를 푼다던지 코드리뷰는 어떻게든 주기적으로 있었으면 좋겠네요.

**Comment by jiwoo-choi** [comment]
👀 간단 내용 정리
1. 알고리즘 교육과정 중에는, 매일 매일 알고리즘 제출은 교육과정 알고리즘 과제로 대체할 수 있습니다!
* 가능하신 분들은 더 풀어주세요
2. 서로서로 코드 리뷰를 위해 문제풀이 인증은 "내 제출" 링크를, 코드 제출 시에는 코드 "공개"를 꼭 해주세요!

<img width="751" alt="스크린샷 2021-02-01 오후 6 34 25" src="https://user-images.githubusercontent.com/18345994/106440361-1ee6bf00-64bc-11eb-849f-03cc46620ef2.png">

3. 월요일 시험이 없는 전 주에, 토요일 오전에 모의 테스트 10AM-12PM (미정)! 
* 금주는 알고리즘 시험 대비용으로 테스트를 보려고 합니다. 2시간 [난이도 골드 1, 실버 3, 브론즈 1]
4. 일요일은 휴식하는걸로!

**Comment by jihyunhillpark** [comment]
wooooooW!!!
정리 요정들이 다 모여있네요..!ㅎ ㄷ ㄷ ㄷ
알고 개미가 되어서 분발하겠슴당 ㅎㅎㅎㅎ!!!
