### ISSUE TITLE
2021/01/24 매일매일 알고리즘 참석확인

### ISSUE THREAD

**Issue by jiwoo-choi** [jiwoo-choi/coding-study#2]
오늘도 화이팅입니다!
제출기한 : 1월 25일 (월) 오전 7AM 까지.

**Comment by jiwoo-choi** [comment]
https://www.acmicpc.net/problem/1010
다리 놓기
채점번호 : 25624936

https://www.acmicpc.net/problem/1018 
체스판 다시 칠하기 
채점번호: 25627557

오늘 실버문제 기준으로 문제를 골라서 풀었는데, 생각보다 문제가 간단해서 두개를 풀었어요.

**Comment by jeesooyaa** [comment]
https://www.acmicpc.net/problem/1330
두 수 비교하기
채점 번호: 25620965

https://www.acmicpc.net/problem/9498
시험 성적
채점 번호: 25630117

https://www.acmicpc.net/problem/2753
윤년
채점 번호: 25630649

https://www.acmicpc.net/problem/14681
사분면 고르기
채점 번호: 25633446

if문 사용 문제 몇 개 풀어봤습니다.

**Comment by hoonti06** [comment]
[내리막길](https://www.acmicpc.net/problem/1520)
채점번호 : 25634077

**Comment by jihyunhillpark** [comment]
저는 밤늦게 풀다가 잠들었는데 오늘7시 이후 아침에 풀어서 1/25로 올릴게요~~
