### ISSUE TITLE
문제 출제하는 방법.

### ISSUE THREAD

**Issue by jiwoo-choi** [jiwoo-choi/coding-study#20]
혹시 본인만의 모의고사를 풀고 싶거나, 출제하고 싶으신 분들을 위해 설명드립니다. 
그렇게 어렵지 않아요!

Boj의 모웹사이트인 Solved.ac는 백준문제의 필터링 검색시스템을 지원합니다.

<img width="1208" alt="스크린샷 2021-02-04 오후 9 35 29" src="https://user-images.githubusercontent.com/18345994/106893581-1a770c00-6731-11eb-8ca2-34c533bfafc1.png">

## 1. 아무도 풀지 않은것을 찾고싶을 땐,
```
~solved_by:faker  // faker가 풀지 않은 문제 중에 (Not : ~ )
solved_by:faker //  faker가 푼 문제 중에.
```

## 2. 테마별로 찾고 싶을 땐,
```
tag:stack (스택)
tag:implementation (구현)
```
태그 리스트는 아래를 참조
https://solved.ac/problems/tags

## 3. 티어별로 찾고 싶을 땐,
```
tier:s1 // 실버 1만.
tier:s1.. // 실버 1 이상. ( ".." : ~이상)
tier:s1..g5 // 실버 1과 골드 5 사이
```
## 4 최소 푼 횟수 (높으면 높을수록 인증된 문제일 확률이 높습니다.)
```
solved:1000.. // 1000명 이상
```

## 5. 예제
```
~solved_by:faker tier:s5..s1 solved:500.. tag:stack // faker에 의해 풀리지 않았으며, 티어는 s5~s1, 최소 500명 이상이 풀었고, 스택 문제만 뽑아달라. 
```
[쿼리결과](https://solved.ac/search?query=~solved_by:faker%20tier:s5..s1%20solved:500..%20tag:stack%20)

**Comment by jihyunhillpark** [comment]
![image](https://user-images.githubusercontent.com/29705409/106910532-a8102700-6744-11eb-8943-7fbf537eee15.png)
크~🍯정보 감사합니다!!

**Comment by jeesooyaa** [comment]
나도 지현이처럼 짤이나 이모티콘이라도 넣고 싶은데 둘 다 모르겠군....
지우오빠 항상 이렇게 정리 잘해주셔서 너무 고마워요!🍯(-> 지현이꺼 복사해서 쓰기..♥)
