### ISSUE TITLE
코딩스터디 봇 2.0 업데이트!

### ISSUE THREAD

**Issue by jiwoo-choi** [jiwoo-choi/coding-study#96]
- 참여율 데이터가 많아진 만큼 차트 정보도 제공합니다.
- 기존의 데이터 중 에 몇가지 데이터가 맞지않는것들을 수정하였습니다.
- 버그를 수정하고 프로젝트 구조를 변경하였습니다.
- 매달 참여율 50%를 달성해봐요!
- <img width="711" alt="스크린샷 2021-03-26 오전 1 55 16" src="https://user-images.githubusercontent.com/18345994/112512024-5300a100-8dd6-11eb-958c-8e6f72a01785.png">

**Comment by hoonti06** [comment]
완전 멋있어!!

**Comment by jeesooyaa** [comment]
★★★빛이 난다...!★★★
★★빛★★지★★우★★
